name 'filezilla'
maintainer 'Lance Powell'
maintainer_email 'lanceraymondpowell@gmail.com'
license 'all_rights'
license 'Apache v2.0'
description 'Installs/Configures FileZilla'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
supports 'windows'
supports 'redhat'
supports 'centos'
supports 'ubuntu'
depends 'windows'
depends 'yum'
version '1.3.2'